---
- type: replace
  path: /networks/name=default
  value:
    name: default
    subnets:
    - azs: [z1, z2, z3]
      cloud_properties:
        name: random
      gateway: 10.144.0.1
      range: 10.144.0.0/16
      reserved:
      - 10.144.0.1
      static:
      - 10.144.0.2 - 10.144.0.127
      - 10.144.1.0 - 10.144.1.127
      - 10.144.2.0 - 10.144.2.127
      - 10.144.3.0 - 10.144.3.127
