#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")"/.. && pwd)"
output_dir="$root_dir"/output/cache
imgscf_dir="$root_dir"/cf
ops_dir="$root_dir"/cf/cf-operations
while getopts "c:" arg; do
  case $arg in
    c) cf_deployment="$(cd $OPTARG && pwd)"
      ;;
  esac
done
for var in cf_deployment; do
  if [[ -z ${!var:-} ]]; then
    echo "USAGE: generate-cf-manifest -c <path-to-cf-deployment>"
    exit 1
  fi
done
set -x

echo "CF_DEPLOYMENT: ${cf_deployment}"
echo "OPS_DIR: ${ops_dir}"
echo "OUTPUT_DIR: ${output_dir}"

    # -o "${cf_deployment}"/operations/experimental/skip-consul-cell-registrations.yml \
    # -o "${cf_deployment}"/operations/experimental/skip-consul-locks.yml \
 
pushd "${cf_deployment}"
  bosh int cf-deployment.yml \
    -o "${cf_deployment}"/operations/use-compiled-releases.yml \
    \
    -o "${cf_deployment}"/operations/experimental/disable-consul.yml \
    -o "${cf_deployment}"/operations/bosh-lite.yml \
    -o "${cf_deployment}"/operations/experimental/disable-consul-bosh-lite.yml \
    \
    -o "${ops_dir}"/allow-local-docker-registry.yml \
    -o "${ops_dir}"/garden-disable-app-armour.yml \
    -o "${ops_dir}"/collocate-tcp-router.yml \
    -o "${ops_dir}"/set-cfdev-subnet.yml \
    -o "${ops_dir}"/lower-memory.yml \
    -o "${ops_dir}"/remove-smoke-test.yml \
    -o "${ops_dir}"/low-tcp-ports.yml \
    -o "${ops_dir}"/add-analytics-user.yml \
    \
    -v cf_admin_password=admin \
    -v uaa_admin_client_secret=admin-client-secret \
    > "${output_dir}/deployment.yml"

  bosh int iaas-support/bosh-lite/cloud-config.yml \
    -o "${ops_dir}"/set-cloud-config-subnet.yml \
    > "${output_dir}/cloud-config.yml"
popd